# For standard Spring Boot parameters see:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 8090


spring:
# APPLICATION NAME
  application:
    name: profile
# PROFILE    
  profiles:
    active:
    - dev
# MONGO    
  data:
    mongodb:
      uri: mongodb://localhost/spring
# RABBIT      
  rabbitmq:
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
      
# PROFILE SENDER      
        sendProfileCreatedEvent:
          destination: profile-created
          group: profile-created

        sendProfileUpdatedEvent:
          destination: profile-updated
          group: profile-updated

        sendProfileDeletedEvent:
          destination: profile-deleted
          group: profile-deleted

